# Generated by Django 3.1.7 on 2021-03-26 16:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='qtd_vezes',
            field=models.IntegerField(default=0, verbose_name='Quantidade de vezes da mudança do preço'),
        ),
        migrations.CreateModel(
            name='CompareProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('preco_produto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço do produto')),
                ('loja', models.CharField(max_length=25, verbose_name='Loja')),
                ('promocao', models.BooleanField(default=False, verbose_name='Possui Promoção?')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='core.produto')),
            ],
            options={
                'verbose_name_plural': 'Compare produtos',
            },
        ),
    ]
