# Generated by Django 3.1.7 on 2021-03-25 16:12

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='descricao', unique=True),
        ),
    ]
