# Generated by Django 3.1.7 on 2021-03-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_compareproduto_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareproduto',
            name='preco_produto',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Preço do produto'),
        ),
    ]
