# Generated by Django 3.1.7 on 2021-03-29 14:40

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210328_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContadorLoja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('loja', models.CharField(max_length=25, verbose_name='Loja')),
                ('qtd_vezes', models.IntegerField(default=0, verbose_name='Quantidade de vezes que a loja foi mais barata')),
            ],
            options={
                'verbose_name': 'Contador Loja',
            },
        ),
        migrations.RemoveField(
            model_name='compareproduto',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='qtd_vezes',
        ),
    ]
