# Generated by Django 3.1.7 on 2021-03-30 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_compareproduto_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareproduto',
            name='loja',
            field=models.CharField(max_length=25, null=True, verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='compareproduto',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='core.produto'),
            preserve_default=False,
        ),
    ]
