# Generated by Django 3.1.7 on 2021-03-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210329_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareproduto',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='core.produto'),
        ),
    ]
