# Generated by Django 3.1.7 on 2021-03-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210331_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compareproduto',
            name='produto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='compare', to='core.produto'),
            preserve_default=False,
        ),
    ]
